runtime: python38 

instance_class: F1

env_variables:
  MYSQL_USER: "root" # please put in your credentials
  MYSQL_PASSWORD: "123" # please put in your credentials
  MYSQL_DB: "RateMyApt" # please put in your credentials
  MYSQL_HOST: "35.184.70.12" # please put in your credentials

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles